sylius_ui:
    events:
        sylius.shop.layout.topbar:
            blocks:
                blog_link:
                    template: "@MonsieurBizSyliusBlogPlugin/Shop/Layout/Topbar/_blogLink.html.twig"
                    priority: 15
                case_study_link:
                    template: "@MonsieurBizSyliusBlogPlugin/Shop/Layout/Topbar/_caseStudyLink.html.twig"
                    priority: 14
