monsieurbiz_blog_admin_tag:
    resource: |
        section: admin
        alias: monsieurbiz_blog.tag
        path: /blog/tag
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        except: ['show']
        grid: monsieurbiz_blog_admin_tag
        vars:
            index:

    type: sylius.resource

monsieurbiz_blog_admin_article:
    resource: |
        section: admin
        alias: monsieurbiz_blog.article
        path: /blog/articles
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        except: ['show', 'create']
        grid: monsieurbiz_blog_admin_article_blog
        vars:
            index:
                icon: 'newspaper'
    type: sylius.resource

monsieurbiz_blog_admin_article_create:
    path: /blog/article/new
    methods: [GET, POST]
    defaults:
        _controller: monsieurbiz_blog.controller.article::createAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/shared/crud/create.html.twig"
            factory:
                method: createNewWithType
                arguments:
                    - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE

monsieurbiz_blog_admin_case_study:
    condition: "env('MONSIEURBIZ_SYLIUS_BLOG_ENABLE_CASE_STUDIES') == 'true'"
    resource: |
        section: admin
        alias: monsieurbiz_blog.case_study
        path: /blog/case-studies
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        except: ['show', 'create']
        grid: monsieurbiz_blog_admin_article_case_study
        vars:
            index:
                icon: 'crosshairs'
    type: sylius.resource

monsieurbiz_blog_admin_case_study_create:
    path: /blog/case-study/new
    condition: "env('MONSIEURBIZ_SYLIUS_BLOG_ENABLE_CASE_STUDIES') == 'true'"
    methods: [GET, POST]
    defaults:
        _controller: monsieurbiz_blog.controller.case_study::createAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/shared/crud/create.html.twig"
            factory:
                method: ["expr:service('monsieurbiz_blog.factory.article')", "createNewWithType"]
                arguments:
                    - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE

monsieurbiz_blog_admin_author:
    resource: |
        section: admin
        alias: monsieurbiz_blog.author
        path: /blog/authors
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        except: ['show']
        grid: monsieurbiz_blog_admin_author
    type: sylius.resource

monsieurbiz_blog_admin_blog_preview:
    path: /blog/article/preview/{id}
    defaults:
        _controller: monsieurbiz_blog.controller.article::previewAction
        template: '@MonsieurBizSyliusBlogPlugin\admin\article\preview.html.twig'
        _sylius:
            section: shop

monsieurbiz_blog_admin_case_study_preview:
    path: /blog/case-study/preview/{id}
    condition: "env('MONSIEURBIZ_SYLIUS_BLOG_ENABLE_CASE_STUDIES') == 'true'"
    defaults:
        _controller: monsieurbiz_blog.controller.article::previewAction
        template: '@MonsieurBizSyliusBlogPlugin\admin\article\preview.html.twig'
        _sylius:
            section: shop

# For blog and case studies
monsieurbiz_blog_admin_article_update_state:
    path: /blog/articles/{id}/{state}
    methods: [PUT]
    defaults:
        _controller: monsieurbiz_blog.controller.article::applyStateMachineTransitionAction
        _sylius:
            event: $state
            section: admin
            permission: true
            state_machine:
                graph: !php/const \MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::GRAPH
                transition: $state
            redirect: referer
            flash: monsieurbiz_blog.blog.article.$state
