monsieurbiz_blog_admin_tag:
    resource: |
        section: admin
        alias: monsieurbiz_blog.tag
        path: /blog/tag
        templates: "@MonsieurBizSyliusBlogPlugin/Admin/Tag"
        redirect: update
        only: ['update', 'delete']
        vars:
            all:
                subheader: monsieurbiz_blog.ui.manage_your_blog_tags
                index:
                    route:
                        name: monsieurbiz_blog_admin_tag_create
    type: sylius.resource

monsieurbiz_blog_admin_tag_index:
    path: /blog/tags
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: monsieurbiz_blog_admin_tag_create
        permanent: true
        keepQueryParams: true

monsieurbiz_blog_admin_tag_create:
    path: /blog/tag/new
    methods: [ GET, POST ]
    defaults:
        _controller: monsieurbiz_blog.controller.tag::createAction
        _sylius:
            section: admin
            permission: true
            template: "@MonsieurBizSyliusBlogPlugin/Admin/Tag/create.html.twig"
            factory:
                method: createNew
            redirect:
                route: monsieurbiz_blog_admin_tag_create
            vars:
                subheader: monsieurbiz_blog.ui.manage_your_blog_tags
                index:
                    route:
                        name: 'monsieurbiz_blog_admin_tag_create'

monsieurbiz_blog_admin_partial_tags_tree:
    path: /_partial/blog/tags/tree
    methods: [GET]
    defaults:
        _controller: monsieurbiz_blog.controller.tag::indexAction
        _sylius:
            template: $template
            repository:
                method: findHydratedRootNodes
            permission: true

monsieurbiz_blog_admin_article:
    resource: |
        section: admin
        alias: monsieurbiz_blog.article
        path: /blog/articles
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: index
        except: ['show', 'create']
        grid: monsieurbiz_blog_admin_article_blog
        vars:
            index:
                icon: 'newspaper'
            update:
                templates:
                    toolbar: "@MonsieurBizSyliusBlogPlugin/Admin/Article/Update/_toolbar.html.twig"
    type: sylius.resource

monsieurbiz_blog_admin_article_create:
    path: /blog/article/new
    methods: [GET, POST]
    defaults:
        _controller: monsieurbiz_blog.controller.article::createAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Crud/create.html.twig"
            factory:
                method: createNewWithType
                arguments:
                    - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE

monsieurbiz_blog_admin_case_study:
    resource: |
        section: admin
        alias: monsieurbiz_blog.case_study
        path: /blog/case-studies
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: index
        except: ['show', 'create']
        grid: monsieurbiz_blog_admin_article_case_study
        vars:
            index:
                icon: 'crosshairs'
            update:
                templates:
                    toolbar: "@MonsieurBizSyliusBlogPlugin/Admin/Article/Update/_toolbar.html.twig"
    type: sylius.resource

monsieurbiz_blog_admin_case_study_create:
    path: /blog/case-study/new
    methods: [GET, POST]
    defaults:
        _controller: monsieurbiz_blog.controller.case_study::createAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Crud/create.html.twig"
            factory:
                method: ["expr:service('monsieurbiz_blog.factory.article')", "createNewWithType"]
                arguments:
                    - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE

monsieurbiz_blog_admin_article_update_state:
    path: /blog/articles/{id}/{state}
    methods: [PUT]
    defaults:
        _controller: monsieurbiz_blog.controller.article::applyStateMachineTransitionAction
        _sylius:
            event: $state
            section: admin
            permission: true
            state_machine:
                graph: !php/const \MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::GRAPH
                transition: $state
            redirect: referer
            flash: monsieurbiz_blog.blog.article.$state

monsieurbiz_blog_admin_author:
    resource: |
        section: admin
        alias: monsieurbiz_blog.author
        path: /blog/authors
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        except: ['show']
        grid: monsieurbiz_blog_admin_author
    type: sylius.resource
