
monsieurbiz_blog_shop:
    resource: "@MonsieurBizSyliusBlogPlugin/Resources/config/routes/shop/blog.yaml"
    prefix: /blog

monsieurbiz_case_study_shop:
    resource: "@MonsieurBizSyliusBlogPlugin/Resources/config/routes/shop/case_study.yaml"
    prefix: /case-studies
