framework:
    workflows:
        !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::GRAPH:
            type: state_machine
            marking_store:
                type: method
                property: state
            supports:
                - MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface
            initial_marking: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::STATE_DRAFT
            places:
                - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::STATE_DRAFT
                - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::STATE_PUBLISHED
            transitions:
                !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::TRANSITION_PUBLISH:
                    from:
                        - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::STATE_DRAFT
                    to: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::STATE_PUBLISHED
