liip_imagine:
    filter_sets:
        monsieurbiz_blog_image_large_thumbnail:
            filters:
                thumbnail: { size: [800, 800], mode: outbound }
        monsieurbiz_blog_image_thumbnail:
            filters:
                thumbnail: { size: [260, 260], mode: outbound }
        monsieurbiz_blog_image_og_image: ~
