services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusBlogPlugin\:
        resource: '../../*'
        exclude: '../../{Component,Entity,Migrations}'

    # Add menu item in admin panel
    MonsieurBiz\SyliusBlogPlugin\EventListener\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main }
    # Form types
    MonsieurBiz\SyliusBlogPlugin\Form\Type\TagType:
        arguments:
            $dataClass: '%monsieurbiz_blog.model.tag.class%'
            $validationGroups: ['monsieurbiz']

    MonsieurBiz\SyliusBlogPlugin\Form\Type\TagTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_blog.model.tag_translation.class%'
            $validationGroups: ['monsieurbiz']

    MonsieurBiz\SyliusBlogPlugin\Form\Type\ArticleType:
        arguments:
            $dataClass: '%monsieurbiz_blog.model.article.class%'
            $validationGroups: ['monsieurbiz']

    MonsieurBiz\SyliusBlogPlugin\Form\Type\ArticleTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_blog.model.article_translation.class%'
            $validationGroups: ['monsieurbiz']

    MonsieurBiz\SyliusBlogPlugin\Form\Type\AuthorType:
        arguments:
            $dataClass: '%monsieurbiz_blog.model.author.class%'
            $validationGroups: [ 'monsieurbiz' ]

    # Menus
    MonsieurBiz\SyliusBlogPlugin\Menu\AdminArticleUpdateMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: monsieurbiz_blog.admin.article.update }

    # Fixtures
    MonsieurBiz\SyliusBlogPlugin\Fixture\Factory\ArticleFixtureFactory:
        arguments:
            $fileLocator: '@file_locator'
            $defaultLocaleCode: '%locale%'
            $publicDir: '%sylius_core.public_dir%'

    MonsieurBiz\SyliusBlogPlugin\Fixture\Factory\AuthorFixtureFactory:
        arguments:
            $fileLocator: '@file_locator'
            $publicDir: '%sylius_core.public_dir%'

    # Live components
    sylius_admin.monsieurbiz_blog.twig.component.tag.form:
        autoconfigure: false
        class: MonsieurBiz\SyliusBlogPlugin\Component\TagFormComponent
        arguments:
            - '@monsieurbiz_blog.repository.tag'
            - '@form.factory'
            - '%monsieurbiz_blog.model.tag.class%'
            - 'MonsieurBiz\SyliusBlogPlugin\Form\Type\TagType'
        tags:
            - { name: 'sylius.live_component.admin', key: 'sylius_admin:monsieurbiz_blog:tag:form' }

    sylius_admin.monsieurbiz_blog.twig.component.article.form:
        autoconfigure: false
        class: MonsieurBiz\SyliusBlogPlugin\Component\ArticleFormComponent
        arguments:
            - '@monsieurbiz_blog.repository.article'
            - '@form.factory'
            - '%monsieurbiz_blog.model.article.class%'
            - 'MonsieurBiz\SyliusBlogPlugin\Form\Type\ArticleType'
        tags:
            - { name: 'sylius.live_component.admin', key: 'sylius_admin:monsieurbiz_blog:article:form' }
