MonsieurBiz\SyliusBlogPlugin\Entity\Article:
    constraints:
        -   MonsieurBiz\SyliusBlogPlugin\Validator\Constraints\UniqueSlugByTypeAndChannel:
                groups: [monsieurbiz]
    properties:
        tags:
            -   NotBlank:
                    groups: [ monsieurbiz ]
            -   Count:
                    min: 1
                    groups: [ monsieurbiz ]
        translations:
            -   Valid:
                    groups: [ monsieurbiz ]
