MonsieurBiz\SyliusBlogPlugin\Entity\ArticleTranslation:
    properties:
        title:
            -   NotBlank:
                    groups: [ monsieurbiz ]
            -   Length:
                    min: 2
                    max: 255
                    groups: [ monsieurbiz ]
        slug:
            -   NotBlank:
                    groups: [ monsieurbiz ]
            -   Length:
                    min: 2
                    max: 255
                    groups: [ monsieurbiz ]
        description:
            -   NotBlank:
                    groups: [ monsieurbiz ]
        content:
            -   NotBlank:
                    groups: [ monsieurbiz ]
