sylius_grid:
    grids:
        # Prototype used for blog and case study
        monsieurbiz_blog_shop_article: &monsieurbiz_blog_shop_article
            sorting:
                publishedAt: desc
            limits: [9]
            fields:
                id:
                    label: sylius.ui.id
                    type: string
                    sortable: ~
                publishedAt:
                    type: datetime
                    sortable: ~
                    label: monsieurbiz_blog.ui.published_at

        monsieurbiz_blog_shop_article_blog: 
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_blog.model.article.class%'
                    repository:
                        method: createShopListQueryBuilderByType
                        arguments:
                            locale: "expr:service('sylius.context.locale').getLocaleCode()"
                            type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            tag: null
            <<: *monsieurbiz_blog_shop_article

        monsieurbiz_blog_shop_article_case_study: 
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_blog.model.case_study.class%'
                    repository:
                        method: createShopListQueryBuilderByType
                        arguments:
                            locale: "expr:service('sylius.context.locale').getLocaleCode()"
                            type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            tag: null
            <<: *monsieurbiz_blog_shop_article
