sylius_grid:
    grids:
        # Prototype used for blog and case study
        monsieurbiz_blog_shop_tag_article: &monsieurbiz_blog_shop_tag_article
            sorting:
                publishedAt: desc
            limits: [9]
            fields:
                id:
                    label: sylius.ui.id
                    type: string
                    sortable: ~
                title:
                    type: string
                    label: monsieurbiz_blog.ui.title
                channels:
                    type: twig
                    label: sylius.ui.channels
                    options:
                        template: '@SyliusAdmin/Grid/Field/_channels.html.twig'
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/state.html.twig"
                        vars:
                            labels: "@MonsieurBizSyliusBlogPlugin/Admin/Article/State"
                updatedAt:
                    type: datetime
                    sortable: ~
                    label: sylius.ui.updating_date
                publishedAt:
                    type: datetime
                    sortable: ~
                    label: monsieurbiz_blog.ui.published_at

        monsieurbiz_blog_shop_tag_article_blog:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_blog.model.article.class%'
                    repository:
                        method: createShopListQueryBuilderByType
                        arguments:
                            locale: "expr:service('sylius.context.locale').getLocaleCode()"
                            type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            tag: "expr:notFoundOnNull(service('monsieurbiz_blog.repository.tag').findOneBySlug($slug, service('sylius.context.locale').getLocaleCode()))"
            <<: *monsieurbiz_blog_shop_tag_article

        monsieurbiz_blog_shop_tag_article_case_study:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_blog.model.case_study.class%'
                    repository:
                        method: createShopListQueryBuilderByType
                        arguments:
                            locale: "expr:service('sylius.context.locale').getLocaleCode()"
                            type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            tag: "expr:notFoundOnNull(service('monsieurbiz_blog.repository.tag').findOneBySlug($slug, service('sylius.context.locale').getLocaleCode()))"
            <<: *monsieurbiz_blog_shop_tag_article
