sylius_grid:
    grids:
        monsieurbiz_blog_admin_tag:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_blog.model.tag.class%'
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                id: desc
            filters:
                name:
                    type: string
                    label: monsieurbiz_blog.ui.title
                    options:
                        fields: [translation.name]
            fields:
                id:
                    label: sylius.ui.id
                    type: string
                    sortable: ~
                name:
                    type: string
                    label: monsieurbiz_blog.ui.title
                    sortable: translation.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
