monsieurbiz_blog_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_blog.controller.article::indexAction
        _sylius:
            template: "@MonsieurBizSyliusBlogPlugin/Shop/Article/index.html.twig"
            grid: monsieurbiz_blog_shop_article_blog
            parameters:
                type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE

monsieurbiz_blog_tag_show:
    path: /tag/{slug}
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_blog.controller.article::indexAction
        _sylius:
            template: "@MonsieurBizSyliusBlogPlugin/Shop/Article/index.html.twig"
            grid: monsieurbiz_blog_shop_tag_article_blog
            parameters:
                tag: "expr:notFoundOnNull(service('monsieurbiz_blog.repository.tag').findOneBySlug($slug, service('sylius.context.locale').getLocaleCode()))"
                type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE

monsieurbiz_blog_article_show:
    path: /{slug}
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_blog.controller.article::showAction
        _sylius:
            template: "@MonsieurBizSyliusBlogPlugin/Shop/Article/show.html.twig"
            repository:
                method: findOnePublishedBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE
                    - "expr:service('sylius.context.channel').getChannel()"
            parameters:
                type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::BLOG_TYPE
