monsieurbiz_case_study_index:
    path: /
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_blog.controller.case_study::indexAction
        _sylius:
            template: "@MonsieurBizSyliusBlogPlugin/Shop/CaseStudy/index.html.twig"
            grid: monsieurbiz_blog_shop_article_case_study
            parameters:
                type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE

monsieurbiz_case_study_tag_show:
    path: /tag/{slug}
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_blog.controller.case_study::indexAction
        _sylius:
            template: "@MonsieurBizSyliusBlogPlugin/Shop/CaseStudy/index.html.twig"
            grid: monsieurbiz_blog_shop_tag_article_case_study
            parameters:
                tag: "expr:notFoundOnNull(service('monsieurbiz_blog.repository.tag').findOneBySlug($slug, service('sylius.context.locale').getLocaleCode()))"
                type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE

monsieurbiz_case_study_article_show:
    path: /{slug}
    methods: [ GET ]
    defaults:
        _controller: monsieurbiz_blog.controller.case_study::showAction
        _sylius:
            template: "@MonsieurBizSyliusBlogPlugin/Shop/CaseStudy/show.html.twig"
            repository:
                method: findOnePublishedBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE
                    - "expr:service('sylius.context.channel').getChannel()"
            parameters:
                type: !php/const MonsieurBiz\SyliusBlogPlugin\Entity\ArticleInterface::CASE_STUDY_TYPE
